import "./globals.css";



import LeftBar from "./component/layout/left-bar";
import Header from "./component/layout/header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >




        <div className="fixed left-0 top-0 mt-4 ms-4 h-[96%] bg-[#181A1D] w-[97px] rounded-[20px] text-white p-3">
          <LeftBar/>
        </div>
        <div className="border border-[#373737] rounded-2xl mt-4 ml-32 mr-4 mb-4 pb-4">
        <Header/>
        {children}
        </div>
     {/* <div className="flex">

 <div className="h-screen">
   <div className="bg-(--dark1) w-[97px] min-w-[97px] h-[96%] 
                  rounded-[20px] text-white p-3 mt-4 ms-4">
    <LeftBar />
  </div>
 </div>

  <div className="flex-1 border border-(--grey1) rounded-2xl 
                  mt-4 ml-4 mr-4 pb-6 mb-4 ">
    <Header />
    {children}
  </div>

</div> */}



      </body>
    </html>
  );
}
